/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Usuario { 
    id?: number;
    nome?: string | null;
    email?: string | null;
    passwd?: string | null;
    permission?: string | null;
}

